name: Test Build

on:
  workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib libcurl4-openssl-dev

    - name: Setup VS2019
      if: matrix.os == 'windows-latest'
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

